### ISSUE TITLE
Companion V3 Midi Error

### ISSUE THREAD

**Issue by bigz200** [bitfocus/companion-module-renewedvision-propresenter#156]
When trying to upgrade to Companion V3, I get an error when the module tries to connect. I'm not even able to adjust the settings to maybe disable the midi connection. Below is what I beleve is the error causing it not to load.

```
Error: Failed to find binding for midi
    at h (/opt/companion/module-legacy/manifests/companion-module-renewedvision-propresenter/index.js:1:163902)
    at 24110 (/opt/companion/module-legacy/manifests/companion-module-renewedvision-propresenter/index.js:1:82707)
    at n (/opt/companion/module-legacy/manifests/companion-module-renewedvision-propresenter/index.js:1:206649)
    at 87228 (/opt/companion/module-legacy/manifests/companion-module-renewedvision-propresenter/index.js:1:155846)
    at n (/opt/companion/module-legacy/manifests/companion-module-renewedvision-propresenter/index.js:1:206649)
    at 54688 (/opt/companion/module-legacy/manifests/companion-module-renewedvision-propresenter/index.js:1:84723)
    at n (/opt/companion/module-legacy/manifests/companion-module-renewedvision-propresenter/index.js:1:206649)
    at /opt/companion/module-legacy/manifests/companion-module-renewedvision-propresenter/index.js:1:207484
    at Object.<anonymous> (/opt/companion/module-legacy/manifests/companion-module-renewedvision-propresenter/index.js:1:207586)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

Node.js v18.14.2
```

**Comment by bigz200** [comment]
I just found a duplicate bug report.
