### ISSUE TITLE
Propresenter Module registration failed error

### ISSUE THREAD

**Issue by bbachrachCC** [bitfocus/companion-module-renewedvision-propresenter#184]
**Describe the bug/issue**
I was able to initally load in the Propresenter module, but once it was setup and I tried to go to it again it won't load. I get a "waiting for connection to load." When I go to the log page, I see the following Error:

error: Module registration failed Error: Call timed out
    at t.IpcWrapper.sendWithCb (/Applications/Companion.app/Contents/Resources/bundled-modules/renewedvision-propresenter/main.js:2:304548)
    at /Applications/Companion.app/Contents/Resources/bundled-modules/renewedvision-propresenter/main.js:2:297629

I've tried going to a previous version of companion, but nothing seems to be fixing this? I am on a 2017 iMac i5 running OS Ventura. 

I have this module working correction on many other computers and setups, this is the first time Ive seen this error.

**Comment by byTschus** [comment]
I have the exact same issue!

**Comment by graemearthur** [comment]
I'm also seeing this issue, did anyone find a workaround?

**Comment by byTschus** [comment]
Looking at issue https://github.com/bitfocus/companion-module-renewedvision-propresenter/issues/167 thread they mentioned in the module settings to turn "Type of presentation info requests" from automatic to manual. Not sure what that does and what else it impacts but my connection is now stable with active slides after making that change.
